services:
  db:
    image: postgres:15
    container_name: db_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=weRV!uDdfD
      - POSTGRES_DB=workers_db
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - '8080:80'
    depends_on:
      - db

  remix:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Defining development stage
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pg-data:
